spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fmi?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: fmi
    password: fmi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

