name: "🐞 Bug Report"
description: "버그 발생 시 제보하는 템플릿"
title: "[BUG] "
labels:
  - bug
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      placeholder: "발생한 버그에 대해 간단히 설명해주세요."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 재현 방법
      value: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 기대 동작
      placeholder: "정상적으로 동작해야 하는 내용을 작성해주세요."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 실제 동작
      placeholder: "실제로 어떻게 동작했는지 작성해주세요."
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 환경
      placeholder: "OS/브라우저/앱 버전 등 (예: Windows 11, Chrome 128)"

  - type: textarea
    id: screenshots
    attributes:
      label: 스크린샷
      placeholder: 필요하다면 스크린샷/로그를 첨부해주세요.


