name: 기능/개선 요청
description: 새 기능/개선 제안 이슈 템플릿
title: "[기능] <요약>"
labels:
  - type: feature
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        아래 브랜치 전략을 반드시 따릅니다.
        - 모든 작업은 이슈 기반 브랜치에서 진행합니다.
        - main 브랜치에 직접 push/commit 금지, PR로만 머지합니다.
        - 작업 브랜치는 main에서 생성하며 이름은 이슈 키 그대로 사용합니다. 예) FIND-001
        - 의존 이슈가 있을 경우, 필요한 작업물이 있는 브랜치에서 분기합니다. 예) FIND-002 → FIND-001에서 분기
        - 커밋 메시지는 Conventional Commits 양식을 권장합니다. 예) feat: 기능 요약

        브랜치 생성 예시:
        - main 최신화: `git pull --rebase origin main`
        - 브랜치 생성: `git checkout -b <이슈키>` (예: `git checkout -b FIND-001`)

  - type: input
    id: issue_key
    attributes:
      label: 이슈 키
      description: FIND-001 형태로 작성합니다. 브랜치명으로도 사용됩니다.
      placeholder: FIND-001
    validations:
      required: true

  - type: input
    id: branch_name
    attributes:
      label: 브랜치 이름
      description: 기본은 이슈 키를 그대로 사용합니다. (예: FIND-001)
      placeholder: FIND-001
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 요약
      description: 구현하려는 기능의 한줄 요약
      placeholder: 무엇을, 왜 필요한지 간단히 설명하세요.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 상세 내용
      description: 요구사항, 스펙, 화면/API 변화, 데이터 모델 변경 등 구체적으로 작성합니다.
      placeholder: 수용 기준(AC)과 함께 작성하면 좋아요.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 수용 기준 (Acceptance Criteria)
      description: 완료로 간주하기 위한 테스트 가능한 기준을 나열합니다.
      value: |
        - [ ] <기준 1>
        - [ ] <기준 2>

  - type: textarea
    id: dependencies
    attributes:
      label: 의존 이슈/브랜치
      description: 다른 이슈에 의존한다면 이슈 번호와 베이스로 삼을 브랜치를 명시하세요.
      placeholder: "FIND-002는 FIND-001의 구현물에 의존 → FIND-001 브랜치에서 분기"

  - type: checkboxes
    id: branch_policy
    attributes:
      label: 브랜치/PR 정책 확인
      description: 제출 전 아래 항목을 모두 확인하세요.
      options:
        - label: main에서 브랜치를 생성한다 (예외적으로 의존 브랜치에서 분기 가능)
          required: true
        - label: main에 직접 push/commit 하지 않는다 (반드시 PR로 머지)
          required: true
        - label: PR 대상은 develop 브랜치이다
          required: true
        - label: 커밋 메시지는 Conventional Commits 양식을 따른다 (feat/fix/chore/docs/refactor/test 등)
          required: true


