apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fmi-be
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/find-my-item/FMI-BE.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: fmi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

